name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

version-resolver:
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'bug'
  default: patch

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '✨ Enhancements'
    labels:
      - 'enhancement'
  - title: '🛠️ Refactors'
    labels:
      - 'refactor'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '📖 Documentation'
    labels:
      - 'documentation'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&`'

no-changes-template: 'No changes in this release.'

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

exclude-labels:
  - 'stale'
  - 'duplicate'
