package dev.kotlintls

data class SessionOptions(
    val sessionId: String? = null,
    val headers: Map<String, String> = emptyMap(),
    val connectHeaders: Map<String, List<String>> = emptyMap(),
    val proxy: String? = null,
    val isRotatingProxy: Boolean = false,
    val clientIdentifier: ClientIdentifier = ClientIdentifier.DEFAULT,
    val ja3String: String? = null,
    val customTlsClient: CustomTlsClient? = null,
    val h2Settings: Map<String, UInt> = emptyMap(),
    val h2SettingsOrder: List<String> = emptyList(),
    val pseudoHeaderOrder: List<String> = emptyList(),
    val connectionFlow: UInt = 0u,
    val priorityFrames: List<PriorityFrame> = emptyList(),
    val headerPriority: PriorityParam? = null,
    val certCompressionAlgo: String = "zlib",
    val supportedVersions: List<String> = emptyList(),
    val supportedSignatureAlgorithms: List<String> = emptyList(),
    val keyShareCurves: List<String> = emptyList(),
    val alpnProtocols: List<String> = emptyList(),
    val alpsProtocols: List<String> = emptyList(),
    val serverNameOverwrite: String? = null,
    val streamOutputBlockSize: Int? = null,
    val streamOutputEOFSymbol: String? = null,
    val streamOutputPath: String? = null,
    val localAddress: String? = null,
    val transportOptions: TransportOptions? = null,
    val headerOrder: List<String> = emptyList(),
    val randomTlsExtensionOrder: Boolean = false,
    val forceHttp1: Boolean = false,
    val debug: Boolean = false,
    val insecureSkipVerify: Boolean = false,
    val timeout: Int = 0,
    val disableIPV4: Boolean = false,
    val disableIPV6: Boolean = false,
    val followRedirects: Boolean = false
)
