package dev.kotlintls.models

data class RequestPayload(
    val requestUrl: String,
    val requestMethod: RequestMethod = RequestMethod.GET,
    val requestBody: String? = null,
    val requestCookies: List<Cookie> = emptyList(),
    val tlsClientIdentifier: String? = null,
    val customTlsClient: CustomTlsClient? = null,
    val sessionId: String? = null,
    val followRedirects: Boolean = false,
    val insecureSkipVerify: Boolean = false,
    val isByteResponse: Boolean = false,
    val isByteRequest: Boolean = false,
    val withoutCookieJar: Boolean = false,
    val withCustomCookieJar: Boolean = false,
    val withRandomTLSExtensionOrder: Boolean = false,
    val timeoutSeconds: Int = 30,
    val timeoutMilliseconds: Int = 0,
    val proxyUrl: String? = null,
    val headers: Map<String, String> = emptyMap(),
    val headerOrder: List<String> = emptyList(),
    val defaultHeaders: Map<String, List<String>>? = null,
    val connectHeaders: Map<String, List<String>>? = null,
    val forceHttp1: Boolean = false,
    val disableHttp3: Boolean = false,
    val withProtocolRacing: Boolean = false,
    val disableIPV6: Boolean = false,
    val disableIPV4: Boolean = false,
    val localAddress: String? = null,
    val serverNameOverwrite: String? = null,
    val requestHostOverride: String? = null,
    val certificatePinningHosts: Map<String, List<String>> = emptyMap(),
    val catchPanics: Boolean = false,
    val withDebug: Boolean = false,
    val isRotatingProxy: Boolean = false,
    val streamOutputPath: String? = null,
    val streamOutputBlockSize: Int? = null,
    val streamOutputEOFSymbol: String? = null,
    val transportOptions: TransportOptions? = null
)
